//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string accountid { get; set; }
        public string accountnumber { get; set; }
        public string address1_addressid { get; set; }
        public string address2_addressid { get; set; }
        public string masterid { get; set; }
        public string name { get; set; }
        public string parentaccountid { get; set; }
        public string parentaccountidname { get; set; }
        public string parentaccountidyominame { get; set; }
        public string ownerid { get; set; }
        public string Mark { get; set; }
        public Nullable<int> statecode { get; set; }
        public string statecodename { get; set; }
        public Nullable<int> statuscode { get; set; }
        public string statuscodename { get; set; }
        public string createbyname { get; set; }
        public string createdbyyominame { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    }
}
