//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_Contact
    {
        public string UniqueId { get; set; }
        public Nullable<System.DateTime> CreateTimestamp { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<System.DateTime> MergeTimestamp { get; set; }
        public Nullable<short> PublicPrivate { get; set; }
        public string RecordManager { get; set; }
        public string Company { get; set; }
        public string Contact { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string IDStatus { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string Pager { get; set; }
        public string Salutation { get; set; }
        public Nullable<System.DateTime> lastMeeting { get; set; }
        public Nullable<System.DateTime> LastReach { get; set; }
        public Nullable<System.DateTime> LastAttempt { get; set; }
        public Nullable<System.DateTime> LetterDate { get; set; }
        public string Title { get; set; }
        public string Assistant { get; set; }
        public string lastresults { get; set; }
        public string ReferredBy { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string AltPhone { get; set; }
        public string Contact2 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneExt { get; set; }
        public string faxExt { get; set; }
        public string AltPhoneExt { get; set; }
        public string AsstTitle { get; set; }
        public string AsstPhone { get; set; }
        public string AsstPhoneExt { get; set; }
        public string Department { get; set; }
        public string Spouse { get; set; }
        public string RecordCreator { get; set; }
        public string WebSite { get; set; }
        public Nullable<short> ContactType { get; set; }
        public string EmailAddress { get; set; }
        public string Note { get; set; }
        public string EmailLogin { get; set; }
        public string EmailSystem { get; set; }
        public string Contacted { get; set; }
        public string InterestLevel { get; set; }
        public string DoNotSendInfo { get; set; }
        public string TotBeds { get; set; }
    }
}
