//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class ax_B1DIEvents
    {
        public string ColKeysList { get; set; }
        public string ColValuesList { get; set; }
        public string dbName { get; set; }
        public Nullable<int> nbColumns { get; set; }
        public string objType { get; set; }
        public string transType { get; set; }
        public long id { get; set; }
        public Nullable<System.DateTime> createOn { get; set; }
        public string SyncFlg { get; set; }
    }
}
