//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CONTR_BILLING_REQ
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_ContractNo { get; set; }
        public string U_BeginPeriod { get; set; }
        public string U_BillingTerm { get; set; }
        public Nullable<int> U_RecruAmount { get; set; }
        public Nullable<int> U_InvAmt { get; set; }
        public Nullable<int> U_SO_Amt { get; set; }
        public string U_Status { get; set; }
        public Nullable<int> U_ContrCaseNo { get; set; }
        public string U_CustomerNo { get; set; }
    }
}
