//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OMPI
    {
        public string ItemCode { get; set; }
    }
}
