//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Q_COMMISSION
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> U_InvoiceNo { get; set; }
        public Nullable<int> U_LineNo { get; set; }
        public Nullable<int> U_RequestAmt { get; set; }
        public Nullable<int> U_PaidAmt { get; set; }
        public string U_TransType { get; set; }
        public string U_SalesName { get; set; }
        public Nullable<int> U_SalesEmpCode { get; set; }
        public string U_PeriodCode { get; set; }
        public Nullable<System.DateTime> U_TransDate { get; set; }
        public string U_Status { get; set; }
        public string U_Approval { get; set; }
        public Nullable<System.DateTime> U_RequestDate { get; set; }
        public Nullable<int> U_Rate { get; set; }
        public Nullable<int> U_InvAmt { get; set; }
        public string U_SalesCat { get; set; }
        public Nullable<System.DateTime> U_InvDate { get; set; }
        public string U_CommGroup { get; set; }
        public string U_InvoiceType { get; set; }
    }
}
