//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_QADJ
    {
        public string Period { get; set; }
        public int DocNum { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Business_Div { get; set; }
        public string SO_Type { get; set; }
        public string InvoiceTypes { get; set; }
        public string Customer_Name { get; set; }
        public string SlpName { get; set; }
        public string Dscription { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public string SalesGroupName { get; set; }
        public string SalesGroupRate { get; set; }
        public Nullable<decimal> SalesGroupEarnAmt { get; set; }
        public string CSR_Name { get; set; }
        public Nullable<decimal> CSREarnAmt { get; set; }
        public string VPName { get; set; }
        public string VPRate { get; set; }
        public Nullable<decimal> VPEarnAmt { get; set; }
        public Nullable<decimal> TotalPayAmt { get; set; }
        public string DocTypes { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Customer_Code { get; set; }
        public string Strategic_Acct { get; set; }
        public Nullable<short> Manufacture_Name { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Commission_Group { get; set; }
        public string ITSD_Contract { get; set; }
        public Nullable<int> SO_No_ { get; set; }
        public string FirmName { get; set; }
        public string SalesCat { get; set; }
        public string U_SOEntBy { get; set; }
        public string U_NAME { get; set; }
        public string ItmsGrpNam { get; set; }
        public int LineNum { get; set; }
        public string FrgnName { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string State { get; set; }
        public string WeekNo { get; set; }
    }
}
