//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SO_SUFFIX_1
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_Billable { get; set; }
        public string U_Warranty { get; set; }
        public string U_Detail { get; set; }
        public string U_OEMWarr { get; set; }
        public string U_BillToOEM { get; set; }
        public string U_RevCatagory { get; set; }
        public string U_TransType { get; set; }
    }
}
