//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_activity
    {
        public string activityid { get; set; }
        public Nullable<int> activitytypecode { get; set; }
        public string activitytypecodename { get; set; }
        public Nullable<int> actualdurationminutes { get; set; }
        public Nullable<System.DateTime> actualend { get; set; }
        public Nullable<System.DateTime> actualstart { get; set; }
        public string createdbyname { get; set; }
        public string createdbyyominame { get; set; }
        public string createdonbehalfby { get; set; }
        public string createdonhehalfbyname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string description { get; set; }
        public string ownerid { get; set; }
        public string owneridname { get; set; }
        public Nullable<int> owneridtype { get; set; }
        public string owneridyominame { get; set; }
        public string regardingobjectid { get; set; }
        public string regardingobjectidname { get; set; }
        public string regardingobjectidyominame { get; set; }
        public Nullable<int> regardingobjecttypecode { get; set; }
        public Nullable<int> scheduleddurationminutes { get; set; }
        public Nullable<int> statecode { get; set; }
        public string statecodename { get; set; }
        public string subject { get; set; }
    }
}
