//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Account
    {
        public string AccountId { get; set; }
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string SyncCompleted { get; set; }
        public string SyncBackId { get; set; }
        public string Name { get; set; }
    }
}
