//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionNotification
    {
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string ObjectType { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> NumOfColsInKey { get; set; }
        public string ListOfKeyColsTabDel { get; set; }
        public string ListOfColsValTabDel { get; set; }
        public int SeqNo { get; set; }
        public string SynFlg { get; set; }
        public string Result { get; set; }
        public string A1Flg { get; set; }
        public string A2Flg { get; set; }
        public string A3Flg { get; set; }
        public string A4Flg { get; set; }
        public string U1Flg { get; set; }
        public string U2Flg { get; set; }
        public string U3Flg { get; set; }
    }
}
