//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Q100.B1WS_Messages {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MessagesService", ConfigurationName="B1WS_Messages.MessagesServiceSoap")]
    public interface MessagesServiceSoap {
        
        // CODEGEN: Generating message contract since the operation GetInbox is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="MessagesService/GetInbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAP_Q100.B1WS_Messages.GetInboxResponse GetInbox(SAP_Q100.B1WS_Messages.GetInboxRequest request);
        
        // CODEGEN: Generating message contract since the operation GetOutbox is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="MessagesService/GetOutbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAP_Q100.B1WS_Messages.GetOutboxResponse GetOutbox(SAP_Q100.B1WS_Messages.GetOutboxRequest request);
        
        // CODEGEN: Generating message contract since the operation GetSentMessages is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="MessagesService/GetSentMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAP_Q100.B1WS_Messages.GetSentMessagesResponse GetSentMessages(SAP_Q100.B1WS_Messages.GetSentMessagesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="MessagesService/GetMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAP_Q100.B1WS_Messages.GetMessageResponse GetMessage(SAP_Q100.B1WS_Messages.GetMessageRequest request);
        
        // CODEGEN: Generating message contract since the operation SendMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="MessagesService/SendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAP_Q100.B1WS_Messages.SendMessageResponse SendMessage(SAP_Q100.B1WS_Messages.SendMessageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public partial class MsgHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private MsgHeaderServiceName serviceNameField;
        
        private bool serviceNameFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MsgHeaderServiceName ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceNameSpecified {
            get {
                return this.serviceNameFieldSpecified;
            }
            set {
                this.serviceNameFieldSpecified = value;
                this.RaisePropertyChanged("ServiceNameSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MsgHeaderServiceName {
        
        /// <remarks/>
        MessagesService,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MessagesService")]
    public partial class GetInbox : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public partial class MessageHeadersMessageHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private bool codeFieldSpecified;
        
        private MessageHeadersMessageHeaderReceived receivedField;
        
        private bool receivedFieldSpecified;
        
        private MessageHeadersMessageHeaderRead readField;
        
        private bool readFieldSpecified;
        
        private System.DateTime receivedDateField;
        
        private bool receivedDateFieldSpecified;
        
        private System.DateTime receivedTimeField;
        
        private bool receivedTimeFieldSpecified;
        
        private System.DateTime sentDateField;
        
        private bool sentDateFieldSpecified;
        
        private System.DateTime sentTimeField;
        
        private bool sentTimeFieldSpecified;
        
        /// <remarks/>
        public long Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
                this.RaisePropertyChanged("CodeSpecified");
            }
        }
        
        /// <remarks/>
        public MessageHeadersMessageHeaderReceived Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
                this.RaisePropertyChanged("Received");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceivedSpecified {
            get {
                return this.receivedFieldSpecified;
            }
            set {
                this.receivedFieldSpecified = value;
                this.RaisePropertyChanged("ReceivedSpecified");
            }
        }
        
        /// <remarks/>
        public MessageHeadersMessageHeaderRead Read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
                this.RaisePropertyChanged("Read");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadSpecified {
            get {
                return this.readFieldSpecified;
            }
            set {
                this.readFieldSpecified = value;
                this.RaisePropertyChanged("ReadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReceivedDate {
            get {
                return this.receivedDateField;
            }
            set {
                this.receivedDateField = value;
                this.RaisePropertyChanged("ReceivedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceivedDateSpecified {
            get {
                return this.receivedDateFieldSpecified;
            }
            set {
                this.receivedDateFieldSpecified = value;
                this.RaisePropertyChanged("ReceivedDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime ReceivedTime {
            get {
                return this.receivedTimeField;
            }
            set {
                this.receivedTimeField = value;
                this.RaisePropertyChanged("ReceivedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceivedTimeSpecified {
            get {
                return this.receivedTimeFieldSpecified;
            }
            set {
                this.receivedTimeFieldSpecified = value;
                this.RaisePropertyChanged("ReceivedTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SentDate {
            get {
                return this.sentDateField;
            }
            set {
                this.sentDateField = value;
                this.RaisePropertyChanged("SentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SentDateSpecified {
            get {
                return this.sentDateFieldSpecified;
            }
            set {
                this.sentDateFieldSpecified = value;
                this.RaisePropertyChanged("SentDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime SentTime {
            get {
                return this.sentTimeField;
            }
            set {
                this.sentTimeField = value;
                this.RaisePropertyChanged("SentTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SentTimeSpecified {
            get {
                return this.sentTimeFieldSpecified;
            }
            set {
                this.sentTimeFieldSpecified = value;
                this.RaisePropertyChanged("SentTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageHeadersMessageHeaderReceived {
        
        /// <remarks/>
        tNO,
        
        /// <remarks/>
        tYES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageHeadersMessageHeaderRead {
        
        /// <remarks/>
        tNO,
        
        /// <remarks/>
        tYES,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.sap.com/SBO/DIS")]
        public SAP_Q100.B1WS_Messages.MsgHeader MsgHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MessagesService", Order=0)]
        public SAP_Q100.B1WS_Messages.GetInbox GetInbox;
        
        public GetInboxRequest() {
        }
        
        public GetInboxRequest(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.GetInbox GetInbox) {
            this.MsgHeader = MsgHeader;
            this.GetInbox = GetInbox;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInboxResponse", WrapperNamespace="http://www.sap.com/SBO/DIS", IsWrapped=true)]
    public partial class GetInboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sap.com/SBO/DIS", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageHeader", IsNullable=false)]
        public SAP_Q100.B1WS_Messages.MessageHeadersMessageHeader[] MessageHeaders;
        
        public GetInboxResponse() {
        }
        
        public GetInboxResponse(SAP_Q100.B1WS_Messages.MessageHeadersMessageHeader[] MessageHeaders) {
            this.MessageHeaders = MessageHeaders;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MessagesService")]
    public partial class GetOutbox : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOutboxRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.sap.com/SBO/DIS")]
        public SAP_Q100.B1WS_Messages.MsgHeader MsgHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MessagesService", Order=0)]
        public SAP_Q100.B1WS_Messages.GetOutbox GetOutbox;
        
        public GetOutboxRequest() {
        }
        
        public GetOutboxRequest(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.GetOutbox GetOutbox) {
            this.MsgHeader = MsgHeader;
            this.GetOutbox = GetOutbox;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOutboxResponse", WrapperNamespace="http://www.sap.com/SBO/DIS", IsWrapped=true)]
    public partial class GetOutboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sap.com/SBO/DIS", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageHeader", IsNullable=false)]
        public SAP_Q100.B1WS_Messages.MessageHeadersMessageHeader[] MessageHeaders;
        
        public GetOutboxResponse() {
        }
        
        public GetOutboxResponse(SAP_Q100.B1WS_Messages.MessageHeadersMessageHeader[] MessageHeaders) {
            this.MessageHeaders = MessageHeaders;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MessagesService")]
    public partial class GetSentMessages : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSentMessagesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.sap.com/SBO/DIS")]
        public SAP_Q100.B1WS_Messages.MsgHeader MsgHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MessagesService", Order=0)]
        public SAP_Q100.B1WS_Messages.GetSentMessages GetSentMessages;
        
        public GetSentMessagesRequest() {
        }
        
        public GetSentMessagesRequest(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.GetSentMessages GetSentMessages) {
            this.MsgHeader = MsgHeader;
            this.GetSentMessages = GetSentMessages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSentMessagesResponse", WrapperNamespace="http://www.sap.com/SBO/DIS", IsWrapped=true)]
    public partial class GetSentMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sap.com/SBO/DIS", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageHeader", IsNullable=false)]
        public SAP_Q100.B1WS_Messages.MessageHeadersMessageHeader[] MessageHeaders;
        
        public GetSentMessagesResponse() {
        }
        
        public GetSentMessagesResponse(SAP_Q100.B1WS_Messages.MessageHeadersMessageHeader[] MessageHeaders) {
            this.MessageHeaders = MessageHeaders;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MessagesService")]
    public partial class GetMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageHeader messageHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.sap.com/SBO/DIS", Order=0)]
        public MessageHeader MessageHeader {
            get {
                return this.messageHeaderField;
            }
            set {
                this.messageHeaderField = value;
                this.RaisePropertyChanged("MessageHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public partial class MessageHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private bool codeFieldSpecified;
        
        private MessageHeaderReceived receivedField;
        
        private bool receivedFieldSpecified;
        
        private MessageHeaderRead readField;
        
        private bool readFieldSpecified;
        
        private System.DateTime receivedDateField;
        
        private bool receivedDateFieldSpecified;
        
        private System.DateTime receivedTimeField;
        
        private bool receivedTimeFieldSpecified;
        
        private System.DateTime sentDateField;
        
        private bool sentDateFieldSpecified;
        
        private System.DateTime sentTimeField;
        
        private bool sentTimeFieldSpecified;
        
        /// <remarks/>
        public long Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
                this.RaisePropertyChanged("CodeSpecified");
            }
        }
        
        /// <remarks/>
        public MessageHeaderReceived Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
                this.RaisePropertyChanged("Received");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceivedSpecified {
            get {
                return this.receivedFieldSpecified;
            }
            set {
                this.receivedFieldSpecified = value;
                this.RaisePropertyChanged("ReceivedSpecified");
            }
        }
        
        /// <remarks/>
        public MessageHeaderRead Read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
                this.RaisePropertyChanged("Read");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadSpecified {
            get {
                return this.readFieldSpecified;
            }
            set {
                this.readFieldSpecified = value;
                this.RaisePropertyChanged("ReadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReceivedDate {
            get {
                return this.receivedDateField;
            }
            set {
                this.receivedDateField = value;
                this.RaisePropertyChanged("ReceivedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceivedDateSpecified {
            get {
                return this.receivedDateFieldSpecified;
            }
            set {
                this.receivedDateFieldSpecified = value;
                this.RaisePropertyChanged("ReceivedDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime ReceivedTime {
            get {
                return this.receivedTimeField;
            }
            set {
                this.receivedTimeField = value;
                this.RaisePropertyChanged("ReceivedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceivedTimeSpecified {
            get {
                return this.receivedTimeFieldSpecified;
            }
            set {
                this.receivedTimeFieldSpecified = value;
                this.RaisePropertyChanged("ReceivedTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SentDate {
            get {
                return this.sentDateField;
            }
            set {
                this.sentDateField = value;
                this.RaisePropertyChanged("SentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SentDateSpecified {
            get {
                return this.sentDateFieldSpecified;
            }
            set {
                this.sentDateFieldSpecified = value;
                this.RaisePropertyChanged("SentDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime SentTime {
            get {
                return this.sentTimeField;
            }
            set {
                this.sentTimeField = value;
                this.RaisePropertyChanged("SentTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SentTimeSpecified {
            get {
                return this.sentTimeFieldSpecified;
            }
            set {
                this.sentTimeFieldSpecified = value;
                this.RaisePropertyChanged("SentTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageHeaderReceived {
        
        /// <remarks/>
        tNO,
        
        /// <remarks/>
        tYES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageHeaderRead {
        
        /// <remarks/>
        tNO,
        
        /// <remarks/>
        tYES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long userField;
        
        private bool userFieldSpecified;
        
        private MessagePriority priorityField;
        
        private bool priorityFieldSpecified;
        
        private string subjectField;
        
        private string textField;
        
        private long attachmentField;
        
        private bool attachmentFieldSpecified;
        
        private MessageMessageDataColumn[] messageDataColumnsField;
        
        private MessageRecipient[] recipientCollectionField;
        
        /// <remarks/>
        public long User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserSpecified {
            get {
                return this.userFieldSpecified;
            }
            set {
                this.userFieldSpecified = value;
                this.RaisePropertyChanged("UserSpecified");
            }
        }
        
        /// <remarks/>
        public MessagePriority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
                this.RaisePropertyChanged("PrioritySpecified");
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        public long Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
                this.RaisePropertyChanged("Attachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttachmentSpecified {
            get {
                return this.attachmentFieldSpecified;
            }
            set {
                this.attachmentFieldSpecified = value;
                this.RaisePropertyChanged("AttachmentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageDataColumn", IsNullable=false)]
        public MessageMessageDataColumn[] MessageDataColumns {
            get {
                return this.messageDataColumnsField;
            }
            set {
                this.messageDataColumnsField = value;
                this.RaisePropertyChanged("MessageDataColumns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Recipient", IsNullable=false)]
        public MessageRecipient[] RecipientCollection {
            get {
                return this.recipientCollectionField;
            }
            set {
                this.recipientCollectionField = value;
                this.RaisePropertyChanged("RecipientCollection");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessagePriority {
        
        /// <remarks/>
        pr_Low,
        
        /// <remarks/>
        pr_Normal,
        
        /// <remarks/>
        pr_High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public partial class MessageMessageDataColumn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private MessageMessageDataColumnLink linkField;
        
        private bool linkFieldSpecified;
        
        private MessageMessageDataColumnMessageDataLine[] messageDataLinesField;
        
        /// <remarks/>
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        public MessageMessageDataColumnLink Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("Link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinkSpecified {
            get {
                return this.linkFieldSpecified;
            }
            set {
                this.linkFieldSpecified = value;
                this.RaisePropertyChanged("LinkSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageDataLine", IsNullable=false)]
        public MessageMessageDataColumnMessageDataLine[] MessageDataLines {
            get {
                return this.messageDataLinesField;
            }
            set {
                this.messageDataLinesField = value;
                this.RaisePropertyChanged("MessageDataLines");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageMessageDataColumnLink {
        
        /// <remarks/>
        tNO,
        
        /// <remarks/>
        tYES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public partial class MessageMessageDataColumnMessageDataLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private string objectField;
        
        private string objectKeyField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        public string Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
                this.RaisePropertyChanged("Object");
            }
        }
        
        /// <remarks/>
        public string ObjectKey {
            get {
                return this.objectKeyField;
            }
            set {
                this.objectKeyField = value;
                this.RaisePropertyChanged("ObjectKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public partial class MessageRecipient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userCodeField;
        
        private MessageRecipientUserType userTypeField;
        
        private bool userTypeFieldSpecified;
        
        private string nameToField;
        
        private MessageRecipientSendEmail sendEmailField;
        
        private bool sendEmailFieldSpecified;
        
        private string emailAddressField;
        
        private MessageRecipientSendSMS sendSMSField;
        
        private bool sendSMSFieldSpecified;
        
        private string cellularNumberField;
        
        private MessageRecipientSendFax sendFaxField;
        
        private bool sendFaxFieldSpecified;
        
        private string faxNumberField;
        
        private MessageRecipientSendInternal sendInternalField;
        
        private bool sendInternalFieldSpecified;
        
        /// <remarks/>
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
                this.RaisePropertyChanged("UserCode");
            }
        }
        
        /// <remarks/>
        public MessageRecipientUserType UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("UserType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserTypeSpecified {
            get {
                return this.userTypeFieldSpecified;
            }
            set {
                this.userTypeFieldSpecified = value;
                this.RaisePropertyChanged("UserTypeSpecified");
            }
        }
        
        /// <remarks/>
        public string NameTo {
            get {
                return this.nameToField;
            }
            set {
                this.nameToField = value;
                this.RaisePropertyChanged("NameTo");
            }
        }
        
        /// <remarks/>
        public MessageRecipientSendEmail SendEmail {
            get {
                return this.sendEmailField;
            }
            set {
                this.sendEmailField = value;
                this.RaisePropertyChanged("SendEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendEmailSpecified {
            get {
                return this.sendEmailFieldSpecified;
            }
            set {
                this.sendEmailFieldSpecified = value;
                this.RaisePropertyChanged("SendEmailSpecified");
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        public MessageRecipientSendSMS SendSMS {
            get {
                return this.sendSMSField;
            }
            set {
                this.sendSMSField = value;
                this.RaisePropertyChanged("SendSMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendSMSSpecified {
            get {
                return this.sendSMSFieldSpecified;
            }
            set {
                this.sendSMSFieldSpecified = value;
                this.RaisePropertyChanged("SendSMSSpecified");
            }
        }
        
        /// <remarks/>
        public string CellularNumber {
            get {
                return this.cellularNumberField;
            }
            set {
                this.cellularNumberField = value;
                this.RaisePropertyChanged("CellularNumber");
            }
        }
        
        /// <remarks/>
        public MessageRecipientSendFax SendFax {
            get {
                return this.sendFaxField;
            }
            set {
                this.sendFaxField = value;
                this.RaisePropertyChanged("SendFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendFaxSpecified {
            get {
                return this.sendFaxFieldSpecified;
            }
            set {
                this.sendFaxFieldSpecified = value;
                this.RaisePropertyChanged("SendFaxSpecified");
            }
        }
        
        /// <remarks/>
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
                this.RaisePropertyChanged("FaxNumber");
            }
        }
        
        /// <remarks/>
        public MessageRecipientSendInternal SendInternal {
            get {
                return this.sendInternalField;
            }
            set {
                this.sendInternalField = value;
                this.RaisePropertyChanged("SendInternal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendInternalSpecified {
            get {
                return this.sendInternalFieldSpecified;
            }
            set {
                this.sendInternalFieldSpecified = value;
                this.RaisePropertyChanged("SendInternalSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageRecipientUserType {
        
        /// <remarks/>
        rt_RandomUser,
        
        /// <remarks/>
        rt_ContactPerson,
        
        /// <remarks/>
        rt_InternalUser,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageRecipientSendEmail {
        
        /// <remarks/>
        tNO,
        
        /// <remarks/>
        tYES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageRecipientSendSMS {
        
        /// <remarks/>
        tNO,
        
        /// <remarks/>
        tYES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageRecipientSendFax {
        
        /// <remarks/>
        tNO,
        
        /// <remarks/>
        tYES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sap.com/SBO/DIS")]
    public enum MessageRecipientSendInternal {
        
        /// <remarks/>
        tNO,
        
        /// <remarks/>
        tYES,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.sap.com/SBO/DIS")]
        public SAP_Q100.B1WS_Messages.MsgHeader MsgHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MessagesService", Order=0)]
        public SAP_Q100.B1WS_Messages.GetMessage GetMessage;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.GetMessage GetMessage) {
            this.MsgHeader = MsgHeader;
            this.GetMessage = GetMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageResponse", WrapperNamespace="http://www.sap.com/SBO/DIS", IsWrapped=true)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sap.com/SBO/DIS", Order=0)]
        public SAP_Q100.B1WS_Messages.Message Message;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(SAP_Q100.B1WS_Messages.Message Message) {
            this.Message = Message;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MessagesService")]
    public partial class SendMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Message messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.sap.com/SBO/DIS", Order=0)]
        public Message Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.sap.com/SBO/DIS")]
        public SAP_Q100.B1WS_Messages.MsgHeader MsgHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MessagesService", Order=0)]
        public SAP_Q100.B1WS_Messages.SendMessage SendMessage;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.SendMessage SendMessage) {
            this.MsgHeader = MsgHeader;
            this.SendMessage = SendMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageResponse", WrapperNamespace="http://www.sap.com/SBO/DIS", IsWrapped=true)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sap.com/SBO/DIS", Order=0)]
        public SAP_Q100.B1WS_Messages.MessageHeader MessageHeader;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(SAP_Q100.B1WS_Messages.MessageHeader MessageHeader) {
            this.MessageHeader = MessageHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessagesServiceSoapChannel : SAP_Q100.B1WS_Messages.MessagesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagesServiceSoapClient : System.ServiceModel.ClientBase<SAP_Q100.B1WS_Messages.MessagesServiceSoap>, SAP_Q100.B1WS_Messages.MessagesServiceSoap {
        
        public MessagesServiceSoapClient() {
        }
        
        public MessagesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAP_Q100.B1WS_Messages.GetInboxResponse SAP_Q100.B1WS_Messages.MessagesServiceSoap.GetInbox(SAP_Q100.B1WS_Messages.GetInboxRequest request) {
            return base.Channel.GetInbox(request);
        }
        
        public SAP_Q100.B1WS_Messages.MessageHeadersMessageHeader[] GetInbox(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.GetInbox GetInbox1) {
            SAP_Q100.B1WS_Messages.GetInboxRequest inValue = new SAP_Q100.B1WS_Messages.GetInboxRequest();
            inValue.MsgHeader = MsgHeader;
            inValue.GetInbox = GetInbox1;
            SAP_Q100.B1WS_Messages.GetInboxResponse retVal = ((SAP_Q100.B1WS_Messages.MessagesServiceSoap)(this)).GetInbox(inValue);
            return retVal.MessageHeaders;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAP_Q100.B1WS_Messages.GetOutboxResponse SAP_Q100.B1WS_Messages.MessagesServiceSoap.GetOutbox(SAP_Q100.B1WS_Messages.GetOutboxRequest request) {
            return base.Channel.GetOutbox(request);
        }
        
        public SAP_Q100.B1WS_Messages.MessageHeadersMessageHeader[] GetOutbox(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.GetOutbox GetOutbox1) {
            SAP_Q100.B1WS_Messages.GetOutboxRequest inValue = new SAP_Q100.B1WS_Messages.GetOutboxRequest();
            inValue.MsgHeader = MsgHeader;
            inValue.GetOutbox = GetOutbox1;
            SAP_Q100.B1WS_Messages.GetOutboxResponse retVal = ((SAP_Q100.B1WS_Messages.MessagesServiceSoap)(this)).GetOutbox(inValue);
            return retVal.MessageHeaders;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAP_Q100.B1WS_Messages.GetSentMessagesResponse SAP_Q100.B1WS_Messages.MessagesServiceSoap.GetSentMessages(SAP_Q100.B1WS_Messages.GetSentMessagesRequest request) {
            return base.Channel.GetSentMessages(request);
        }
        
        public SAP_Q100.B1WS_Messages.MessageHeadersMessageHeader[] GetSentMessages(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.GetSentMessages GetSentMessages1) {
            SAP_Q100.B1WS_Messages.GetSentMessagesRequest inValue = new SAP_Q100.B1WS_Messages.GetSentMessagesRequest();
            inValue.MsgHeader = MsgHeader;
            inValue.GetSentMessages = GetSentMessages1;
            SAP_Q100.B1WS_Messages.GetSentMessagesResponse retVal = ((SAP_Q100.B1WS_Messages.MessagesServiceSoap)(this)).GetSentMessages(inValue);
            return retVal.MessageHeaders;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAP_Q100.B1WS_Messages.GetMessageResponse SAP_Q100.B1WS_Messages.MessagesServiceSoap.GetMessage(SAP_Q100.B1WS_Messages.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public SAP_Q100.B1WS_Messages.Message GetMessage(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.GetMessage GetMessage1) {
            SAP_Q100.B1WS_Messages.GetMessageRequest inValue = new SAP_Q100.B1WS_Messages.GetMessageRequest();
            inValue.MsgHeader = MsgHeader;
            inValue.GetMessage = GetMessage1;
            SAP_Q100.B1WS_Messages.GetMessageResponse retVal = ((SAP_Q100.B1WS_Messages.MessagesServiceSoap)(this)).GetMessage(inValue);
            return retVal.Message;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAP_Q100.B1WS_Messages.SendMessageResponse SAP_Q100.B1WS_Messages.MessagesServiceSoap.SendMessage(SAP_Q100.B1WS_Messages.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public SAP_Q100.B1WS_Messages.MessageHeader SendMessage(SAP_Q100.B1WS_Messages.MsgHeader MsgHeader, SAP_Q100.B1WS_Messages.SendMessage SendMessage1) {
            SAP_Q100.B1WS_Messages.SendMessageRequest inValue = new SAP_Q100.B1WS_Messages.SendMessageRequest();
            inValue.MsgHeader = MsgHeader;
            inValue.SendMessage = SendMessage1;
            SAP_Q100.B1WS_Messages.SendMessageResponse retVal = ((SAP_Q100.B1WS_Messages.MessagesServiceSoap)(this)).SendMessage(inValue);
            return retVal.MessageHeader;
        }
    }
}
